### ISSUE TITLE
Replace military ranks with something more friendly

### ISSUE THREAD

**Issue by thomasrudin** [thomasrudin-mt/xp_redo#21]
# Prefixes
* Cobble ...
* Stone ...
* Coal ...
* Iron ...
* Copper ...
* Gold ...
* Diamond ...
* Mese ...
* Lava ...

# Suffixes
* -Peasant
* -Merchant
* -Knight
* -Lord
* -Mayor
* -Master
* -God

**Comment by thomasrudin** [comment]
https://www.minecraftforum.net/forums/support/server-support-and/1922516-minecraft-server-rank-names

**Comment by thomasrudin** [comment]
fixed with rank-mod: https://github.com/thomasrudin-mt/xp_redo_ranks_ores

**Comment by tacotexmex** [comment]
”Cobble Peasant”…😄 Love it!
